/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { urlOpener } from 'utils'

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:f29b681f-bd37-463a-adc5-4b77c96ba0b9',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_yhE8HfPgN',
  aws_user_pools_web_client_id: '8053ac4f-de29-4d9d-9cf8-c36a5ebf7f33',
  aws_appsync_graphqlEndpoint: 'https://gbr5bdlpdbamjnzmxgkrbu3qxy.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'OPENID_CONNECT',
  oauth: {}
}

export default awsmobile
